name: Azure DevOps Link Validation

on:
  pull_request:
    types: [opened, edited, reopened]
  push:
    branches:
      - '*'

jobs:
  validate_azure_devops_links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Check for valid Azure DevOps IDs
        env:
          AZURE_DEVOPS_ORG: "Kyndryl"
          AZURE_DEVOPS_PROJECT: "ResiliencyEng"
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }} # Create a GitHub secret for your Azure DevOps Personal Access Token
        run: |
          # Check for invalid work item IDs in pull request title and commit messages
          set -x

          id=$(git log -1 --pretty=%B | head -n 1 |grep -Eo 'AB#[0-9]+'| cut -d '#' -f 2)
          echo " The is : $id "
          if [[ -z "$id" ]]; then
            echo "Unable to find Ticket ID in commit message. Proceeding with PR title"
            pr_title_id=$(echo "${{ github.event.pull_request.title }}" | grep -Eo 'AB#[0-9]+'| cut -d '#' -f 2)
            id=$pr_title_id
          fi

          # Validate Azure DevOps work item IDs
          response=$(curl -s -u ":$AZURE_DEVOPS_PAT" -X GET "https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_apis/wit/workitems/$id?api-version=6.0")
          if [ "$(echo "$response" | jq '.id')" == "null" ]; then
            echo "Work item with ID $id not found in Azure DevOps."
            exit 1
          else
            echo "The ID is valid"
          fi

