name: "Check Commit Message Format"

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - '*'

jobs:
  check_commit_message_format:
    runs-on: ubuntu-latest
    steps:
      - name: "Check Commit Message Format"
        run: |
          if ! grep -qE "(?<!\w)AB#[0-9]+(?!\w)" $GITHUB_EVENT_PATH; then
            echo "Commit message should contain AB# followed by a number"
            exit 1
          fi
