name: "Check Commit Message Format"

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - '*'

jobs:
  check_commit_message_format:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
           echo "Event path: $GITHUB_EVENT_PATH"
           cat $GITHUB_EVENT_PATH
           
      - name: "Check Commit Message Format"
        run: |
          if ! grep -qE "(^|\s)AB#[0-9]+(\s|$)" $GITHUB_EVENT_PATH; then
            echo "Commit message should contain AB# followed by a number and separated from other text by a space"
            exit 1
          fi
