name: Commit keyword validation
on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - '*'
jobs:
  commit_message_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check commit message
        run: |
          commit_msg=$(git log --format=%B -n 1 $GITHUB_SHA)
          echo $commit_msg
          echo "Okayv1"
          if [[ ! "$commit_msg" =~ ^AB#[0-9]+$ ]]; then
            echo "Error: Commit message must contain 'AB#' followed by ADO ID, in the form AB#ID"
            exit 1
          fi
