name: Pre-commit

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        ls -la 
        pwd
        sudo apt-get update && sudo apt-get install -y python3 python3-pip
        pip3 install pre-commit
    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files
        if ! git log --format=%B -n 1 HEAD | grep -Eq 'AB#[0-9]+'; then
          echo "Commit message must contain AB# followed by a number"
          exit 1
        fi
